return {}
-- return {
--   {
--     "olimorris/codecompanion.nvim",
--     dependencies = {
--       "nvim-lua/plenary.nvim",
--       "nvim-treesitter/nvim-treesitter",
--       "hrsh7th/nvim-cmp", -- Optional: For using slash commands and variables in the chat buffer
--       -- "nvim-telescope/telescope.nvim", -- Optional: For using slash commands
--       { "MeanderingProgrammer/render-markdown.nvim", ft = { "markdown", "codecompanion" } }, -- Optional: For prettier markdown rendering
--       { "stevearc/dressing.nvim", opts = {} }, -- Optional: Improves `vim.ui.select`
--     },
--
--     keys = {
--       -- { "<c-s>", "<CR>", ft = "codecompanion-chat", desc = "Submit Prompt", remap = true },
--       { "<leader>a", "", desc = "+ai", mode = { "n", "v" } },
--       {
--         "<leader>af",
--         "<cmd>CodeCompanionActions<cr>",
--         desc = "Action palette",
--         mode = { "n", "v" },
--       },
--       {
--         "<leader>aa",
--         "<cmd>CodeCompanionChat Toggle<cr>",
--         desc = "Toggle chat",
--         mode = { "n", "v" },
--       },
--       {
--         "<leader>ac",
--         "<cmd>CodeCompanionChat Add<cr>",
--         desc = "Send selection to chat",
--         mode = { "v" },
--       },
--       -- -- Show help actions with telescope
--       -- { "<leader>ad", M.pick("help"), desc = "Diagnostic Help (CodeCompanion)", mode = { "n", "v" } },
--       -- -- Show prompts actions with telescope
--       -- { "<leader>ap", M.pick("prompt"), desc = "Prompt Actions (CodeCompanion)", mode = { "n", "v" } },
--     },
--
--     opts = {
--       display = {
--         chat = {
--           render_headers = false,
--         },
--       },
--     },
--   },
-- }
