return {}
-- return {
--   {
--     "tiagovla/scope.nvim",
--     lazy = false,
--     config = true,
--     keys = {
--       {
--         "<C-S-l>",
--         "<cmd>tabnext<cr>",
--         desc = "Switch to next tab",
--         mode = { "n" },
--       },
--       {
--         "<C-S-h>",
--         "<cmd>tabprevious<cr>",
--         desc = "Switch to previous tab",
--         mode = { "n" },
--       },
--     },
--   },
--
--   {
--     "akinsho/bufferline.nvim",
--     opts = {
--       options = {
--         always_show_bufferline = true,
--       },
--     },
--   },
-- }
